test: &default

  # Credentials for REST APIs
  client_id: AUkeGnfhHAOwzYoStLxF2Y4KpQ9YJr0fzuM5vgfwTReT5_wUeRwxc3zctRdwdq1nhK1Z7b1u7Jd01D4s
  client_secret: EAwP8A6qO9LmKP7RxupgyIcSsKdsHjp7rgh3sSABdLAKeByIVDpxEIv9DZ61gPXXok8gW-DB9exjlzPY

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

#  # Credentials for Classic APIs
#  app_id: APP-80W284485P519543T
#  username: jb-us-seller_api1.paypal.com
#  password: WX4WTU3S8MY44S7F
#  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
#   # With Certificate
#   cert_path: "config/cert_key.pem"
#  sandbox_email_address: LendLord-facilitator@mail.utoronto.ca

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
